### PR TITLE
fix xml parsing problem with stax-api pom

### PR DESCRIPTION
**Pull request by pabl0rg**
added the right import. should build

### CODE REVIEW

**Comment by cbeust** [comment]
Are you sure that dependency shows the problem? It's working for me, do you have another one I can test with?

```
$ ./kobaltw --resolve "javax.xml.stream:stax-api:1.0-2" 
  Downloaded http://repo1.maven.org/maven2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar
  Downloaded http://repo1.maven.org/maven2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.pom
╔════════════════════════════════════════════════════════════════════════════════════════════╗
║                                   javax.xml.stream:stax-api:1.0-2                          ║
║           http://repo1.maven.org/maven2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar ║
╚════════════════════════════════════════════════════════════════════════════════════════════╝

BUILD SUCCESSFUL (2 seconds)

$ 
```

**Comment by pabl0rg** [comment]
I'm on MacOS. Not sure if that's a factor.

./kobaltw --resolve "javax.xml.stream:stax-api:1.0-2"
[Wrapper] /Users/juanliska/Documents/startrack/code/wasabi/./kobaltw already exists, not overwriting it
[Wrapper] /Users/juanliska/Documents/startrack/code/wasabi/./kobalt/wrapper/kobalt-wrapper.jar already exists, not overwriting it
            _  __          _               _   _
           | |/ /   ___   | |__     __ _  | | | |_
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.322

info: PERF: INIT: Compiler initialized in 1062 ms
info: PERF: ANALYZE: 1 files (50 lines) in 1400 ms
info: PERF: GENERATE: 1 files (50 lines) in 264 ms
[Fatal Error] :8:1: Content is not allowed in trailing section.
***** WARNING Exception when trying to resolve dependencies for javax.xml.stream:stax-api:1.0-2: Unable to provision, see the following errors:

1) Error injecting constructor, org.xml.sax.SAXParseException; lineNumber: 8; columnNumber: 1; Content is not allowed in trailing section.
  at com.beust.kobalt.maven.Pom.<init>(Pom.kt:13)
  while locating com.beust.kobalt.maven.Pom annotated with @com.google.inject.internal.UniqueAnnotations$Internal(value=1)

1 error
╔══════════════════════════════════════════════════════════════════════════════════════════╗
║                                  javax.xml.stream:stax-api:1.0-2                         ║
║           https://jcenter.bintray.com/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar ║
╚══════════════════════════════════════════════════════════════════════════════════════════╝

**Comment by cbeust** [comment]
So am I. I just tried again after wiping my whole repo and it worked.

I suspect this is not the dependency causing the problem, can you paste the dependencies in your `Build.kt`? One of them is probably causing this.

**Comment by cbeust** [comment]
By the way, feel free to join us on #kobalt on Slack, will be easier to chat if you have questions.

**Pull request closed without merging**
