### PR TITLE
fixed incremantal building of fatJar

### PR DESCRIPTION
**Pull request by DevCharly**
the time stamps of the included jars and classes folders of other projects were not checked

### CODE REVIEW

**Comment by cbeust** [comment]
We discussed this on Slack and I have a better idea: calculate checksums of the time stamps to implement incremental `assemble`.

**Comment by DevCharly** [comment]
Any news on this one?
The fatJar bug, which this PR would fix, is still there.

Could you merge this PR meanwhile until we have checksums for incremental `assemble`?

**Comment by cbeust** [comment]
Yes, this PR is fine. This makes the jar creation skipped if all the files are up to date but there is still a lot of time spent finding these included files:

```
───── kobalt-plugin-api:assemble
FOUND INCLUDED FILES IN 6005 ms
  Created modules\kobalt-plugin-api\kobaltBuild\libs\kobalt-plugin-api-0.843.jar
FOUND INCLUDED FILES IN 9 ms
  Created modules\kobalt-plugin-api\kobaltBuild\libs\kobalt-plugin-api-0.843-sources.jar
FOUND INCLUDED FILES IN 0 ms
  Created modules\kobalt-plugin-api\kobaltBuild\libs\kobalt-plugin-api-0.843.pom

───── kobalt:assemble
FOUND INCLUDED FILES IN 8525 ms
  Created .\kobaltBuild\libs\kobalt-0.843.jar
FOUND INCLUDED FILES IN 4 ms
FOUND INCLUDED FILES IN 0 ms
  Created .\kobaltBuild\libs\kobalt-0.843.zip
  Created .\kobaltBuild\libs\kobalt-0.843.pom
```

I'm guessing the next step is that when creating a fat jar file, we should look at the time stamp of the included jar file and not the files inside.

**Comment by DevCharly** [comment]
> FOUND INCLUDED FILES IN 8525 ms

This is indeed very slow.
How can I enable this timing output?

> we should look at the time stamp of the included jar file and not the files inside.

Hm, the time stamps of files inside of JARs are checked? Where is this done? Have not found the code...

**Comment by cbeust** [comment]
I just timed this call from `JarGenerator.kt`:

```
    fun generateJar(project: Project, context: KobaltContext, jar: Jar) : File {
        val includedFiles = findIncludedFiles(project, context, jar)  // <-- this takes a while
```

**Comment by cbeust** [comment]
Some more context.

The function that creates jar file takes a boolean called `expandJarFiles`:

```
        return Archives.generateArchive(project, context, jar.name, ".jar", includedFiles,
                true /* expandJarFiles */, jarFactory)
```

This boolean tells the function what to do when one of the included file is a jar file. If that boolean is `true`, that jar file is expanded and the files it contains are added to the jar file (this is what happens for fat jar creation). If it's `false`, the jar file is added as is to the final jar file.

**Pull request merged**
