### PR TITLE
Better last version checker

### PR DESCRIPTION
**Pull request by cy6erGn0m**
Choose latest version according to version number instead of taking the first one in the list.

Don't call getAsString at JsonNull

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
@cbeust notice that currently every ./kobaltw run fails with error like this:

```
Caused by: java.lang.UnsupportedOperationException: JsonNull
        at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
        at com.beust.kobalt.misc.GithubApi$latestKobaltVersion$callable$1.call(GithubApi.kt:34)
        at com.beust.kobalt.misc.GithubApi$latestKobaltVersion$callable$1.call(GithubApi.kt:17)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    ....
```

this is why I think it could be done like this

**Comment by cbeust** [comment]
The error you're seeing is because I'm currently messing with the releases with the github API but you are 100% correct, your approach looks a lot better. Will review shortly.

**Comment by cbeust** [comment]
Looks good to me. Do you mind rebasing so I can merge? If not, I'll do the merge manually.

Thanks!

**Comment by cbeust** [comment]
Just checking: are you still working on that PR?

**Pull request closed without merging**
