### PR TITLE
Remove local files, update gradle

### PR DESCRIPTION
**Pull request by jaredsburrows**
- Removed local IDEA files
- Updated Gradle to 2.11(using `bin` vs `all`)
- Updated `.gitignore` referenced here: https://github.com/joeblau/gitignore.io/issues/184
- Added build status for Travis CI

### CODE REVIEW

**Comment by jaredsburrows** [comment]
@cbeust There is no reason for it to fail. It passed the first one.

**Comment by jaredsburrows** [comment]
@cbeust Fixed.

**Comment by cbeust** [comment]
I'd like to keep the IDEA files since without them, it's harder for someone to import Kobalt in IDEA.

**Comment by jaredsburrows** [comment]
@cbeust I'll close this PR for now. When there is an easy way to "import from kobalt", then I'll re-submit this PR to clean the `.idea` files.

**Pull request closed without merging**
