### PR TITLE
* fix wrapper execution

### PR DESCRIPTION
**Pull request by dmitry-zhuravlev**
* fix wrapper execution

### CODE REVIEW

**Comment by DevCharly** [comment]
Hm. For me, this fix breaks kobaltw.bat.

My Git root is D:\tools\kobalt and double clicking kobaltw.bat in this folder results in following error:
```
Error: Unable to access jarfile D:\tools\kobalt\/../kobalt/wrapper/kobalt-wrapper.jar
```
Removing '../' fixes the problem...

**Comment by cbeust** [comment]
@DevCharly I reverted that fix in the latest release for now.

@dmitry-zhuravlev What was this supposed to fix?

**Comment by dmitry-zhuravlev** [comment]
@cbeust Fix was designed for kobaltw.bat placed in HOME/.kobalt dir. Without ../ this bat will not work.

**Comment by cbeust** [comment]
Then we need to find a way to make it work in both locations. I do this
with the shell version of the wrapper by generating it when Kobalt unzips
it, we should probably do the same thing for kobaltw.bat.
​

-- 
Cédric

**Comment by DevCharly** [comment]
Maybe dist/kobaltw.bat is the right place for ../ ?

**Comment by DevCharly** [comment]
dist/kobaltw already contains ../

**Pull request merged**
