### PR TITLE
proxy handling improved

### PR DESCRIPTION
**Pull request by dmitry-zhuravlev**
* proxy handling improved for repositories defined in transitive dependencies.
proxy config now looks like:
<proxies>
       <proxy>
           <host>mycompany.com</host>
           <port>3128</port>
            <type>http</type>
            <nonProxyHosts>localhost</nonProxyHosts>
       </proxy>
       <proxy>
           <host>mycompany.com</host>
           <port>3128</port>
            <type>https</type>
           <nonProxyHosts>localhost</nonProxyHosts>
       </proxy>
   </proxies>

### CODE REVIEW

**Comment by cbeust** [comment]
It looks like all this PR does is allowing more than one proxy to be defined?

Then I'm not quite sure which one gets picked, are they all tried in order?

**Comment by dmitry-zhuravlev** [comment]
Yep, this allow to define more than one proxy because there is "http" and "https" repositories and hence it should be at least two proxy defined. In most cases http and https proxy is the same, but also it is posible that company have tho separate proxies for each of the protocol. Also in this PR I set proxy in the aether session directly- this fix the problem when repositories defined in transitive dependencies handled without proxy.

**Comment by dmitry-zhuravlev** [comment]
So the strategy is following: for the aether session will be picked up all proxies defined in settings. For repositories in Aether class the first proxy matched by protocol (http/https) will be picked up. For OkHttpClient any first proxy will be picked up.

**Comment by cbeust** [comment]
Got it. Note that your change would break existing users (since you
modified the XML definition) but it's okay for now.

-- 
Cédric


On Wed, Jun 15, 2016 at 12:44 AM, Dmitry Zhuravlev <notifications@github.com

**Comment by dmitry-zhuravlev** [comment]
I think existing users doesn't have proxy definition in settings because this feature didn't documented in http://beust.com/kobalt/documentation/index.html yet.

**Comment by cbeust** [comment]
Yes, that's why I'm fine with this breaking change, pretty sure nobody is
using this feature right now :-)

Just wanted to make sure you were aware.

-- 
Cédric

**Pull request merged**
